version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: autoservice-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_HOST: postgres-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: redis-cache
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      API_NINJAS_URL: ${API_NINJAS_URL}
      API_NINJAS_SECRET_KEY: ${API_NINJAS_SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
